#!/usr/bin/env bash

# A script to make s6 and s6-rc easier to use

# Define colors
RED='\033[0;31m'
YELLOW='\033[0;33m'
GREEN='\033[0;32m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
GRAY='\033[1;30m'
NC='\033[0m'
BOLD='\033[1m'

help-sv() {
    # Function to print usage info
    echo ""
    echo "Usage:"
    echo "------"
    li="s6ctl help|This info"
    li="$li\ns6ctl up SERVICE|Start the service"
    li="$li\ns6ctl down [force] SERVICE|Stop the service"
    li="$li\ns6ctl restart SERVICE|Restart the service"
    li="$li\ns6ctl in BUNDLE add/remove SERVICE|Add or remove service in a bundle"
    li="$li\ns6ctl create BUNDLE SERVICE|Create a new bundle and add a service to it"
    li="$li\ns6ctl delete BUNDLE|Delete a bundle"
    li="$li\ns6ctl log [SERVICE]|Read the log of service or enter the log directory"
    li="$li\ns6ctl log critical|Read the list of critical errors"
    li="$li\ns6ctl log list|List available logs to read"
    li="$li\ns6ctl status [full] SERVICE|Show the status of a service"
    li="$li\ns6ctl cat SERVICE|Write the script of service to stdout"
    li="$li\ns6ctl update|Update the service database"
    li="$li\ns6ctl doctor|Starts the debugger"
    li="$li\ns6ctl docs COMPONENT|Open the documentation on a s6 component"
    li="$li\ns6ctl list all|Lists all services"
    li="$li\ns6ctl list up/down|Lists all services that are currently up or down"
    li="$li\ns6ctl list bundle/longrun/oneshot|Lists all bundles, longruns or oneshots"
    li="$li\ns6ctl list in BUNDLE|Lists all services in the bundle"
    li="$li\ns6ctl list dependencies SERVICE|Lists all dependencies of a service"
    li="$li\ns6ctl list processes SERVICE|Lists all processes of a service"
    printf "$li" | column -t -s "|"
}

whichbundle() {
    # Find wich bundles a service is a part of
    bndllist=""
    bndlnum=$(sudo s6-rc-db list bundles | wc -l)
    for ((i=1; i<=$bndlnum; i++))
    do
        bndlname=$(sudo s6-rc-db list bundles | sed -n "$i"p)
        sudo s6-rc-db contents "$bndlname" | grep -q "$1" && bndllist="$bndllist, $bndlname"
    done
    if [[ -z $bndllist ]]; then
        bndllist="Not in any bundle"
    else
        bndllist=$(echo "$bndllist" | sed 's/, //')
    fi
    echo "$bndllist"
}

readlog() {
    # Read log of specified service or enter the log directory
    if [ -z "$1" ]; then
        cd /var/log && ls
    elif [ "$1" == "list" ]; then
        sudo find /var/log | grep "current" | sed 's+/+ +g' | awk '{print $3}'
    else
        sudo "$PAGER" /var/log/$1/current
    fi
}

bugCheck() {
    # The doctor function
    numsv=$(ls /run/service/ | wc -l)
    chk=0

    # Check for consistency errors in the database
    constdb=$(sudo s6-rc-db check)
    echo ""
    echo "Analyzing..."
    echo "> Checking consistency in database..."

    # Check consistency between s6 and as6-rc
    echo "> Checking consistency between s6 and s6-rc..."
    constrc=$(sudo s6-rc diff)

    # Check for failed services
    echo "> Looking for failed services..."
    chk=""
    for ((i=1; i<=$numsv; i++))
    do
        svname=$(ls /run/service/ | sed -n "$i"p)
        ecode=$(echo "/run/service/$svname" | xargs sudo s6-svstat -e)
        if [ $((ecode)) != -1 ] && [ $((ecode)) != 0 ]; then
            chk="$chk\n$svname encountered an error and exited with exit code: $ecode"
        fi
    done

    if [ -z "$chk" ]; then
        chk="No failed services found"
    fi

    if [ -z "$constdb" ] && [ -z "$constrc" ]; then
        constrc="No consistency errors found"
    fi
    echo "$constdb"
    echo "$constrc"
    printf "$chk"
}

statDesc() {
    # Fetch description of service
    svtype=$(sudo s6-rc-db type "$1")
    echo ""
    li="${BOLD}Name:|${NC}$1"

    svversion=$(echo "$1" | awk '{print tolower($0)}' | xargs -ro pacman -Qs | grep "/$1 " | awk '{print $2}')
    if [ -n "$svversion" ]; then
        li="$li\nVersion:|$svversion"
    fi

    li="$li\nType:|$svtype"

    svbundle=$(whichbundle "$1")
    li="$li\nBundle:|$svbundle"

    description=$(pacman -Qs "$1" | sed -n 2p | sed 's/    //')
    if [ -n "$description" ]; then
        li="$li\nDescription:|$description"
    fi

    printf "$li" | column -t -s "|"
}

statStatus() {
    # Fetch status of service
    # Pass service name as arg1 and title as arg2
    svstatus=$(sudo s6-svstat /run/service/"$1" | awk '{print $1}')
    svtime=$(sudo s6-svstat -t /run/service/"$1")
    svtime=$((svtime/60))
    svpid=$(sudo s6-svstat -p /run/service/"$1")
    ecode=$(sudo s6-svstat -e /run/service/"$1")

    title="${BOLD}$2:${NC}| "
    if [ "$svstatus" == "up" ]; then
        li="Status:|${GREEN}${BOLD}Up${NC}"
        lj="Process:|${PURPLE}$svpid${NC}"
    elif [ "$ecode" == 0 ]; then
        li="Status:|${RED}${BOLD}Down${NC}"
        lj="Exitcode:|${GRAY}$ecode${NC}"
    else
        li="Status:|${RED}${BOLD}Failed${NC}"
        lj="Exitcode:|${RED}$ecode${NC}"
    fi

    li="$li\n$lj"
    li="$li\nUptime:|${CYAN}$svtime min${NC}"
    li="$title\n$li"
    echo "$li"
}

listDeps() {
    # Fetch list of Dependencies
    svdep=$(sudo s6-rc-db dependencies "$1")
    if [ -n "$svdep" ]; then
        printf "${BOLD}Dependencies:${NC}\n"
        echo "$svdep"
        echo ""
    fi
}

listProc() {
    # List processes owned by service
    pidList=""
    dirArray=("/run/service/$1" "/run/service/$1-srv" "/run/service/$1-log")
    for dirs in "${dirArray[@]}";
    do
        if [ -d "$dirs" ]; then
            pid=$(sudo s6-svstat -p "$dirs")
            pidList="$pid $pidList"
        fi
    done
    echo ""
    if [ -n "$pidList" ]; then
        printf "${BOLD}Processes:${NC}\n"
        ps -LfMp $pidList
    fi
}

logTail() {
    # Print the log tail of service
    svlog=/var/log/"$1"/current
    if [ -f $svlog ]; then
        printf "${BOLD}Log tail:${NC}\n"
        tail "$svlog"
        echo ""
    fi
}

stat() {
    # Print all information about a service
    svdir="/etc/s6/sv/$1"
    if [[ -d $svdir ]] || [[ -d $svdir-srv ]]; then
        statDesc "$1"
        echo ""
        svtype=$(sudo s6-rc-db type "$1")
        svcount=$(ls /run/service | grep "$1" | wc  -l)
        if [ "$svtype" == "bundle" ] && [ $((svcount)) == 2 ]; then
            # Longrun with logger
            svstatus=$(sudo s6-svstat /run/service/"$1"-srv | awk '{print $1}')
            svtime=$(sudo s6-svstat -t /run/service/"$1"-srv)
            svtime=$((svtime/60))
            svpid=$(sudo s6-svstat -p /run/service/"$1"-srv)
            ecode=$(sudo s6-svstat -e /run/service/"$1"-srv)

            logstatus=$(sudo s6-svstat /run/service/"$1"-log | awk '{print $1}')
            logtime=$(sudo s6-svstat -t /run/service/"$1"-log)
            logtime=$((logtime/60))
            logpid=$(sudo s6-svstat -p /run/service/"$1"-log)
            logecode=$(sudo s6-svstat -e /run/service/"$1"-log)

            title="${BOLD}Server:${NC}| |${BOLD}Logger:${NC}| "
            if [ "$svstatus" == "up" ]; then
                li="Status:|${GREEN}${BOLD}Up${NC}"
                lj="Process:|${PURPLE}$svpid${NC}"
            elif [ "$ecode" == 0 ]; then
                li="Status:|${RED}${BOLD}Down${NC}"
                lj="Exitcode:|${GRAY}$ecode${NC}"
            else
                li="Status:|${RED}${BOLD}Failed${NC}"
                lj="Exitcode:|${RED}$ecode${NC}"
            fi

            if [ "$logstatus" == "up" ]; then
                li="$li|Status:|${GREEN}${BOLD}Up${NC}"
                lj="$lj|Process:|${PURPLE}$logpid${NC}"
            elif [ "$logecode" == 0 ]; then
                li="$li|Status:|${RED}${BOLD}Down${NC}"
                lj="$lj|Exitcode:|${GRAY}$logecode${NC}"
            else
                li="$li|Status:|${RED}${BOLD}Failed${NC}"
                lj="$lj|Exitcode:|${RED}$logecode${NC}"
            fi
            li="$li\n$lj"
            li="$li\nUptime:|${CYAN}$svtime min${NC}|Uptime:|${CYAN}$logtime min${NC}"
            li="$title\n$li"
            printf "$li" | column -t -s "|"
        elif [ "$svtype" == "longrun" ]; then
            # Longrun
            srv=$(statStatus "$1" "Service")
            printf "$srv" | column -t -s "|"
        fi
        if [ "$2" == "-f" ]; then
            echo ""
            listDeps "$1"
            listProc "$1"
            logTail "$1"
        fi
    else
        echo "$1 is not a service"
    fi
}

listAll() {
    # Fetch a list of services or bundles
    list=$(sudo s6-rc-db list "$1" | sed '/-log/d')
    svnum=$(echo "$list" | wc -l)
    if [ "$1" == "services" ]; then
        li=" : \nService:Type\n-------:----"
    else
        li=" : \n$1\n-------"
    fi
    for ((i=1; i<=$svnum; i++))
    do
        name=$(echo "$list" | sed -n "$i"p)
        if [ "$1" == "services" ]; then
            type=$(sudo s6-rc-db type "$name")
            li="$li\n$name:$type"
        else
            li="$li\n$name"
        fi
    done

    # li=$(echo "$li" | sed 's/-srv//g')
    printf "$li\n : " | sed 's/-srv//g' | column -t -s ":"
    echo "$svnum in total"
}

listLongrun() {
    # List all longruns and show their current status
    # TODO Group -srv and -log so every service is only listed once
    list=$(sudo s6-rc-db list longruns | sed '/.*-log/d')
    svnum=$(echo "$list" | wc -l)
    li=" : : : : \nService:Status:Uptime:PID:Exit code\n-------:------:------:---:---------"

    for ((i=1; i<=$svnum; i++))
    do
        sv=$(echo "$list" | sed -n "$i"p)
        pipe=$(sudo s6-rc-db pipeline "$sv")
        svtime=$(sudo s6-svstat -t /run/service/$sv)
        svtime=$((svtime/60))
        svtime="${CYAN}$svtime min${NC}"

        if [ -n "$pipe" ]; then
            srv="$sv"
            sv=$(echo "$sv" | sed 's/-srv//')
            svstatus=$(sudo s6-svstat /run/service/$srv | awk '{print $1}')
            logger=$(echo "$pipe" | awk '{print $3}')
            logstatus=$(sudo s6-svstat /run/service/$logger | awk '{print $1}')
            if [ $svstatus == "up" ] && [ $logstatus == "up" ]; then
                svid=$(sudo s6-svstat -p /run/service/$srv)
                svid="${PURPLE}$svid${NC}"
                ecode="${GRAY}-${NC}"
                sv="${GREEN}${BOLD}$sv${NC}"
                svstatus="${GREEN}$svstatus${NC}"
            elif [ $svstatus == "up" ]; then
                svid=$(sudo s6-svstat -p /run/service/$srv)
                svid="${PURPLE}$svid${NC}"
                ecode="${GRAY}-${NC}"
                sv="${YELLOW}${BOLD}$sv${NC}"
                svstatus="${YELLOW}partial${NC}"
            else
                svid="${GRAY}-${NC}"
                ecode=$(sudo s6-svstat -e /run/service/$srv)
                if [ $((ecode)) != 0 ]; then
                    ecode="${RED}$ecode${NC}"
                else
                    ecode="${GRAY}$ecode${NC}"
                fi
                sv="${RED}${BOLD}$sv${NC}"
                svstatus="${RED}$svstatus${NC}"
            fi
        else
            svstatus=$(sudo s6-svstat /run/service/$sv | awk '{print $1}')
            if [ $svstatus = "up" ]; then
                svid=$(sudo s6-svstat -p /run/service/$sv)
                svid="${PURPLE}$svid${NC}"
                ecode="${GRAY}-${NC}"
                sv="${GREEN}${BOLD}$sv${NC}"
                svstatus="${GREEN}$svstatus${NC}"
            else
                svid="${GRAY}-${NC}"
                ecode=$(sudo s6-svstat -e /run/service/$sv)
                if [ $((ecode)) != 0 ]; then
                    ecode="${RED}$ecode${NC}"
                else
                    ecode="${GRAY}$ecode${NC}"
                fi
                sv="${RED}${BOLD}$sv${NC}"
                svstatus="${RED}$svstatus${NC}"
            fi
        fi
        li="$li\n$sv:$svstatus:$svtime:$svid:$ecode"
    done

    printf "$li\n : : : : " | column -t -s ":"
    echo "$svnum in total"
}

listUpDown() {
    list=$(listLongrun | grep "$1")
    echo "$list"
}

listInbndl() {
    # List all services in a bundle
    svnum=$(sudo s6-rc-db contents "$1" | wc -l)
    li=" : \nService:Type\n-------:----"
    for ((i=1; i<=$svnum; i++))
    do
        name=$(sudo s6-rc-db contents "$1" | sed -n "$i"p)
        type=$(sudo s6-rc-db type "$name")
        li="$li\n$name:$type"
    done
    printf "$li\n : " | column -t -s ":"
    echo "$svnum in total"
}

catScript() {
    type=$(sudo s6-rc-db type "$1")
    case "$type" in
        "oneshot")
            echo ""
            echo "$1:"
            sudo s6-rc-db script "$1"
            ;;
        "bundle")
                  dir=/etc/s6/sv/"$1"-srv
                  if [ -d "$dir" ]; then
                      echo ""
                      echo "Server:"
                      cat "$dir/run"
                      echo ""
                      echo "Logger:"
                      cat "/etc/s6/sv/$1-log/run"
                  else
                      listInbndl "$1"
                  fi
                  ;;
        "longrun")
            echo ""
            echo "$1:"
            cat "/etc/s6/sv/$1/run"
            ;;
    esac
}

handler() {
    # The handler to change contents of bundle
    if [ "$1" == "add" ];then
        sudo s6-rc-bundle-update add "$2" "$3" && echo "$3 has been added to $2"
    elif [ "$1" == "remove" ]; then
        sudo s6-rc-bundle-update delete "$2" "$3" && echo "$3 has been removed from $2"
    else
        help-sv
    fi
}

listHandler() {
    # The handler for the various list functions
    case "$1" in
        "all") listAll "services" ;;
        "bundles") listAll "bundles" ;;
        "longruns") listLongrun ;;
        "oneshots") listAll "oneshots" ;;
        "in") listInbndl "$2" ;;
        "dependencies") echo "" && listDeps "$2" ;;
        "processes") listProc "$2" ;;
        "up") listUpDown "$1" ;;
        "down") listUpDown "$1" ;;
    esac
}

# The main case handler
case "$1" in
    "help") help-sv ;;
    "doctor") bugCheck ;;
    "update") printf "\nUpdating database...\n" && sudo /usr/share/libalpm/scripts/s6-rc-db-update-hook;;
    "log") readlog "$2" ;;
    "status") [ "$2" == "full" ] && stat "$3" "-f" || stat "$2" ;;
    "up") sudo s6-rc -v 2 -u change "$2" ;;
    "down") [ "$2" == "force" ] && sudo s6-rc -v 2 -D change "$3" || sudo s6-rc -v 2 -d change "$2" ;;
    "restart") echo "Restarting $2" && sudo s6-rc -v 2 -d change "$2" && sudo s6-rc -v 2 -u change "$2" ;;
    "create") sudo s6-rc-bundle add "$2" "$3" && echo "Created the $2 bundle, and added $3 in it" ;;
    "delete") sudo s6-rc-bundle delete "$2" && echo "Deleted the $2 bundle" ;;
    "in") handler "$3" "$2" "$4" ;;
    "list") listHandler "$2" "$3" ;;
    "cat") catScript "$2" ;;
    "docs") links https://skarnet.org/software/"$2" ;;
esac
